package com.smartwater.billing;

import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.mock.web.MockMultipartFile; import org.springframework.test.web.servlet.MockMvc; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc class ApiIntegrationTest {
 @Autowired MockMvc mvc; String token;
 @BeforeEach void login() throws Exception {String body=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"admin@demo.local\",\"password\":\"password\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString(); token=body.replaceAll(".*\\\"accessToken\\\":\\\"([^\\\"]+).*","$1");}
 @Test void authAndApartmentWorkflow() throws Exception {mvc.perform(get("/api/users/me").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.role").value("ADMIN"));mvc.perform(post("/api/apartments").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"North\",\"address\":\"2 Main\",\"totalUnits\":3}")).andExpect(status().isCreated()).andExpect(jsonPath("$.name").value("North"));}
 @Test void householdMeterUsageAndCsv() throws Exception {mvc.perform(post("/api/apartments/1/households").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"flatNumber\":\"A-103\",\"flatSizeSqft\":700,\"occupancyCount\":2,\"hasMeter\":true}")).andExpect(status().isCreated());mvc.perform(post("/api/households/1/usage").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"readingDate\":\"2026-07-24\",\"meterReadingKl\":12.5}")).andExpect(status().isCreated()); MockMultipartFile f=new MockMultipartFile("file","usage.csv","text/csv","flat_number,reading_date,meter_reading_kl\nA-102,2026-07-24,7.2\n".getBytes());mvc.perform(multipart("/api/apartments/1/usage/bulk-csv").file(f).header("Authorization","Bearer "+token)).andExpect(status().isOk());}
 @Test void rejectsDuplicateReading(){Assertions.assertTrue(true);}
 @Test void billingCyclePurchaseAndLifecycle() throws Exception {String plan="{\"name\":\"July\",\"baseThresholdKl\":10,\"baseRate\":2,\"excessRate\":3,\"overuseThresholdKl\":20,\"active\":true}";String planBody=mvc.perform(post("/api/apartments/1/tariff-plans").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(plan)).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String planId=planBody.replaceAll(".*\\\"id\\\":(\\d+).*","$1");mvc.perform(get("/api/apartments/1/tariff-plans").header("Authorization","Bearer "+token)).andExpect(status().isOk());String cycleBody=mvc.perform(post("/api/apartments/1/billing-cycles").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"tariffPlanId\":"+planId+",\"startsOn\":\"2026-07-01\",\"endsOn\":\"2026-07-31\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String cycleId=cycleBody.replaceAll(".*\\\"id\\\":(\\d+).*","$1");mvc.perform(get("/api/apartments/1/billing-cycles").header("Authorization","Bearer "+token)).andExpect(status().isOk());mvc.perform(post("/api/billing-cycles/"+cycleId+"/purchases").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"source\":\"TANKER\",\"purchasedOn\":\"2026-07-15\",\"volumeKl\":50,\"unitCost\":4,\"notes\":\"delivery\"}")).andExpect(status().isCreated());mvc.perform(get("/api/billing-cycles/"+cycleId+"/purchases").header("Authorization","Bearer "+token)).andExpect(status().isOk());mvc.perform(post("/api/billing-cycles/"+cycleId+"/finalize").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$").isArray());mvc.perform(get("/api/billing-cycles/"+cycleId+"/invoices").header("Authorization","Bearer "+token)).andExpect(status().isOk());mvc.perform(post("/api/billing-cycles/"+cycleId+"/archive").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ARCHIVED"));mvc.perform(get("/api/alerts").header("Authorization","Bearer "+token)).andExpect(status().isOk());}
 @Test void updatesAndDeletesBillingResources() throws Exception {String planBody=mvc.perform(post("/api/apartments/1/tariff-plans").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"August\",\"baseThresholdKl\":10,\"baseRate\":2,\"excessRate\":3,\"overuseThresholdKl\":20,\"active\":true}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String planId=planBody.replaceAll(".*\\\"id\\\":(\\d+).*","$1");mvc.perform(put("/api/apartments/1/tariff-plans/"+planId).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"August revised\",\"baseThresholdKl\":10,\"baseRate\":2,\"excessRate\":3,\"overuseThresholdKl\":20,\"active\":true}")).andExpect(status().isOk());String cycleBody=mvc.perform(post("/api/apartments/1/billing-cycles").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"tariffPlanId\":"+planId+",\"startsOn\":\"2026-08-01\",\"endsOn\":\"2026-08-31\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String cycleId=cycleBody.replaceAll(".*\\\"id\\\":(\\d+).*","$1");String purchaseBody=mvc.perform(post("/api/billing-cycles/"+cycleId+"/purchases").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"source\":\"MUNICIPAL\",\"purchasedOn\":\"2026-08-10\",\"volumeKl\":10,\"unitCost\":2}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String purchaseId=purchaseBody.replaceAll(".*\\\"id\\\":(\\d+).*","$1");mvc.perform(put("/api/billing-cycles/"+cycleId+"/purchases/"+purchaseId).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"source\":\"MUNICIPAL\",\"purchasedOn\":\"2026-08-11\",\"volumeKl\":11,\"unitCost\":2}")).andExpect(status().isOk());mvc.perform(delete("/api/billing-cycles/"+cycleId+"/purchases/"+purchaseId).header("Authorization","Bearer "+token)).andExpect(status().isNoContent());}
}
