#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jul 30 15:07:55 IST 2026
prefixes-apache.snapshots.txt.lastUpdated=1785403613465
prefixes-central.txt.lastUpdated=1785403609080
prefixes-flyway-community-db-support.txt.error=Could not transfer metadata /.meta/prefixes.txt from/to flyway-community-db-support (https\://maven.pkg.github.com/flyway/flyway-community-db-support)\: No such host is known (maven.pkg.github.com)
prefixes-flyway-community-db-support.txt/@default-flyway-community-db-support-https\://maven.pkg.github.com/flyway/flyway-community-db-support/.lastUpdated=1785404275939
prefixes-jboss-public-repository-group.txt.error=
prefixes-jboss-public-repository-group.txt.lastUpdated=1785233720268
prefixes-maven-central.txt.lastUpdated=1785403614008
prefixes-oss.snapshots.txt.error=
prefixes-oss.snapshots.txt.lastUpdated=1785403619144
prefixes-ossrh.txt.error=
prefixes-ossrh.txt.lastUpdated=1785403614826
prefixes-ow2-snapshot.txt.lastUpdated=1785403623789
prefixes-plexus.snapshots.txt.error=
prefixes-plexus.snapshots.txt.lastUpdated=1785403612348
prefixes-redshift.txt.error=
prefixes-redshift.txt.lastUpdated=1785403617614
prefixes-repo.gradle.org.txt.error=
prefixes-repo.gradle.org.txt.lastUpdated=1785403616180
prefixes-sonatype-nexus-snapshots.txt.error=
prefixes-sonatype-nexus-snapshots.txt.lastUpdated=1785403611600
prefixes-spring-milestones.txt.error=
prefixes-spring-milestones.txt.lastUpdated=1785403616499
prefixes-spring-release.txt.error=Could not transfer metadata /.meta/prefixes.txt from/to spring-release (https\://repo.spring.io/release)\: No such host is known (repo.spring.io)
prefixes-spring-release.txt/@default-spring-release-https\://repo.spring.io/release/.lastUpdated=1785404275939
prefixes-spring-snapshot.txt.error=
prefixes-spring-snapshot.txt.lastUpdated=1785403615383
