import { useEffect, useState } from 'react'

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'https://smart-water-usage-and-consumer-billing.onrender.com'
const authHeaders = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('smartwater.accessToken')}` })

export default function SuperAdminDashboardPage() {
  const [communities, setCommunities] = useState([])
  const [community, setCommunity] = useState({ name: '', address: '', totalUnits: 1 })
  const [admin, setAdmin] = useState({ communityId: '', name: '', email: '', password: '' })
  const [message, setMessage] = useState('')
  const load = async () => { const r = await fetch(`${apiBaseUrl}/api/super-admin/communities`, { headers: authHeaders() }); if (r.ok) setCommunities(await r.json()) }
  useEffect(() => { load() }, [])
  async function createCommunity(e) { e.preventDefault(); const r = await fetch(`${apiBaseUrl}/api/super-admin/communities`, { method: 'POST', headers: authHeaders(), body: JSON.stringify({ ...community, totalUnits: Number(community.totalUnits) }) }); setMessage(r.ok ? 'Community created.' : 'Could not create community.'); if (r.ok) { setCommunity({ name: '', address: '', totalUnits: 1 }); load() } }
  async function createAdmin(e) { e.preventDefault(); const r = await fetch(`${apiBaseUrl}/api/super-admin/communities/${admin.communityId}/admins`, { method: 'POST', headers: authHeaders(), body: JSON.stringify(admin) }); setMessage(r.ok ? 'Community administrator created.' : 'Could not create administrator.'); if (r.ok) setAdmin({ communityId: '', name: '', email: '', password: '' }) }
  return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">Platform administration</h1><p className="mt-1 text-slate-600">{communities.length} communities · {communities.reduce((n, c) => n + c.totalUnits, 0)} configured units</p>{message && <p className="mt-4 rounded bg-sky-50 p-3 text-sky-800">{message}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><form className="rounded-xl bg-white p-5 shadow" onSubmit={createCommunity}><h2 className="font-semibold">Create community</h2>{['name','address','totalUnits'].map(k => <input key={k} required placeholder={k === 'totalUnits' ? 'Total units' : k[0].toUpperCase()+k.slice(1)} type={k === 'totalUnits' ? 'number' : 'text'} value={community[k]} onChange={e => setCommunity({ ...community, [k]: e.target.value })} className="mt-3 w-full rounded border p-2" />)}<button className="mt-4 rounded bg-sky-600 px-4 py-2 font-medium text-white">Create</button></form><form className="rounded-xl bg-white p-5 shadow" onSubmit={createAdmin}><h2 className="font-semibold">Create community admin</h2><select required value={admin.communityId} onChange={e => setAdmin({ ...admin, communityId: e.target.value })} className="mt-3 w-full rounded border p-2"><option value="">Select community</option>{communities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>{['name','email','password'].map(k => <input key={k} required placeholder={k[0].toUpperCase()+k.slice(1)} type={k === 'password' ? 'password' : k === 'email' ? 'email' : 'text'} value={admin[k]} onChange={e => setAdmin({ ...admin, [k]: e.target.value })} className="mt-3 w-full rounded border p-2" />)}<button className="mt-4 rounded bg-sky-600 px-4 py-2 font-medium text-white">Create admin</button></form></div><section className="mt-6 rounded-xl bg-white p-5 shadow"><h2 className="font-semibold">Communities</h2><ul className="mt-3 divide-y">{communities.map(c => <li key={c.id} className="py-3"><span className="font-medium">{c.name}</span><span className="ml-3 text-slate-600">{c.address} · {c.totalUnits} units</span></li>)}</ul></section></div></main>
}
