spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/water_management_db"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    clean-on-validation-error: true
server:
  port: 8082
app.jwt:
  secret: "smart-water-demo-secret-must-be-at-least-32-characters-long"
  access-minutes: 30
  refresh-days: 7
